package net.appbuilder.shell;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.DownloadManager;
import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Environment;
import android.util.Base64;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.webkit.ConsoleMessage;
import android.webkit.CookieManager;
import android.webkit.GeolocationPermissions;
import android.webkit.JavascriptInterface;
import android.webkit.MimeTypeMap;
import android.webkit.PermissionRequest;
import android.webkit.RenderProcessGoneDetail;
import android.webkit.ServiceWorkerClient;
import android.webkit.ServiceWorkerController;
import android.webkit.URLUtil;
import android.webkit.ValueCallback;
import android.webkit.WebChromeClient;
import android.webkit.WebResourceError;
import android.webkit.WebResourceRequest;
import android.webkit.WebResourceResponse;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.FrameLayout;
import android.widget.Toast;

import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.core.view.WindowInsetsControllerCompat;
import androidx.webkit.WebViewAssetLoader;
import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** WebView shell generated by AppBuilder Engine for web projects. */
public class MainActivity extends Activity {
    private static final String TAG = "AppBuilderShell";
    private static final int REQUEST_FILE_CHOOSER = 1001;
    private static final int REQUEST_GEOLOCATION = 1002;
    private static final int REQUEST_MEDIA = 1003;

    private ShellConfig config;
    private Set<String> declaredPermissions;
    private FrameLayout root;
    private View statusBarBackground;
    private WebView webView;
    private WebViewAssetLoader assetLoader;
    private String downloadScript;
    private volatile String currentHost;

    private ValueCallback<Uri[]> fileCallback;
    private GeolocationPermissions.Callback pendingGeoCallback;
    private String pendingGeoOrigin;
    private PermissionRequest pendingMediaRequest;
    private List<String> pendingMediaResources = Collections.emptyList();
    private View customView;
    private WebChromeClient.CustomViewCallback customViewCallback;
    private BackCallbacks backCallbacks;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        config = ShellConfig.load(this);
        declaredPermissions = readDeclaredPermissions();
        downloadScript = readAsset("appbuilder-downloads.js");

        WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
        root = new FrameLayout(this);
        root.setBackgroundColor(config.backgroundColor);
        webView = new WebView(this);
        webView.setBackgroundColor(config.backgroundColor);
        root.addView(webView, new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        statusBarBackground = new View(this);
        statusBarBackground.setBackgroundColor(config.themeColor);
        root.addView(statusBarBackground, new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 0));
        setContentView(root);
        applySystemBars();
        ViewCompat.setOnApplyWindowInsetsListener(root, (view, insets) -> {
            Insets bars = insets.getInsets(WindowInsetsCompat.Type.systemBars() | WindowInsetsCompat.Type.displayCutout());
            Insets ime = insets.getInsets(WindowInsetsCompat.Type.ime());
            FrameLayout.LayoutParams webParams = (FrameLayout.LayoutParams) webView.getLayoutParams();
            FrameLayout.LayoutParams barParams = (FrameLayout.LayoutParams) statusBarBackground.getLayoutParams();
            if (config.fullscreen || customView != null) {
                webParams.setMargins(0, 0, 0, ime.bottom);
                barParams.height = 0;
            } else {
                webParams.setMargins(bars.left, bars.top, bars.right, Math.max(bars.bottom, ime.bottom));
                barParams.height = bars.top;
            }
            webView.setLayoutParams(webParams);
            statusBarBackground.setLayoutParams(barParams);
            return WindowInsetsCompat.CONSUMED;
        });

        if (Build.VERSION.SDK_INT >= 33) {
            backCallbacks = new BackCallbacks(this, this::handleBack);
        }

        assetLoader = new WebViewAssetLoader.Builder()
                .setDomain(ShellConfig.LOCAL_HOST)
                .addPathHandler("/", new WebRootHandler(getAssets()))
                .build();
        configureWebView();
        registerServiceWorkerClient();

        if (savedInstanceState == null || webView.restoreState(savedInstanceState) == null) {
            webView.loadUrl(config.initialUrl());
        }
    }

    @SuppressLint({"SetJavaScriptEnabled", "JavascriptInterface"})
    private void configureWebView() {
        WebSettings settings = webView.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);
        settings.setMediaPlaybackRequiresUserGesture(false);
        settings.setAllowFileAccess(false);
        settings.setAllowContentAccess(false);
        settings.setUseWideViewPort(true);
        settings.setLoadWithOverviewMode(true);
        settings.setSupportZoom(false);
        settings.setBuiltInZoomControls(false);
        settings.setDisplayZoomControls(false);
        settings.setSupportMultipleWindows(false);
        settings.setJavaScriptCanOpenWindowsAutomatically(false);
        settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);
        settings.setUserAgentString(settings.getUserAgentString() + " AppBuilderShell/1.0");

        boolean debuggable = (getApplicationInfo().flags & ApplicationInfo.FLAG_DEBUGGABLE) != 0;
        WebView.setWebContentsDebuggingEnabled(debuggable);

        webView.addJavascriptInterface(new AndroidBridge(), "AppBuilderAndroid");
        if (downloadScript != null && WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)) {
            Set<String> origins = new HashSet<>();
            origins.add(ShellConfig.LOCAL_ORIGIN);
            if (config.isRemote()) {
                Uri start = Uri.parse(config.startUrl);
                origins.add(start.getScheme() + "://" + start.getHost());
            }
            WebViewCompat.addDocumentStartJavaScript(webView, downloadScript, origins);
            downloadScript = null;
        }

        webView.setWebViewClient(new ShellWebViewClient());
        webView.setWebChromeClient(new ShellChromeClient());
        webView.setDownloadListener(this::onDownload);
    }

    private void registerServiceWorkerClient() {
        try {
            ServiceWorkerController.getInstance().setServiceWorkerClient(new ServiceWorkerClient() {
                @Override
                public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
                    return assetLoader.shouldInterceptRequest(request.getUrl());
                }
            });
        } catch (RuntimeException e) {
            Log.w(TAG, "Service workers are not supported by this WebView", e);
        }
    }

    private void applySystemBars() {
        WindowInsetsControllerCompat controller = WindowCompat.getInsetsController(getWindow(), getWindow().getDecorView());
        if (config.fullscreen || customView != null) {
            if (Build.VERSION.SDK_INT >= 28) {
                WindowManager.LayoutParams attributes = getWindow().getAttributes();
                attributes.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
                getWindow().setAttributes(attributes);
            }
            controller.setSystemBarsBehavior(WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
            controller.hide(WindowInsetsCompat.Type.systemBars());
        } else {
            controller.show(WindowInsetsCompat.Type.systemBars());
            controller.setAppearanceLightStatusBars(ShellConfig.isLight(config.themeColor));
            controller.setAppearanceLightNavigationBars(ShellConfig.isLight(config.backgroundColor));
        }
    }

    // ------------------------------------------------------------ navigation

    private final class ShellWebViewClient extends WebViewClient {
        @Override
        public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request) {
            return assetLoader.shouldInterceptRequest(request.getUrl());
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
            return handleNavigation(request.getUrl());
        }

        @Override
        public void onPageStarted(WebView view, String url, Bitmap favicon) {
            currentHost = Uri.parse(url).getHost();
        }

        @Override
        public void onPageFinished(WebView view, String url) {
            if (downloadScript != null && config.isAppHost(Uri.parse(url).getHost())) {
                view.evaluateJavascript(downloadScript, null);
            }
            updateBackCallback();
        }

        @Override
        public void doUpdateVisitedHistory(WebView view, String url, boolean isReload) {
            currentHost = Uri.parse(url).getHost();
            updateBackCallback();
        }

        @Override
        public void onReceivedError(WebView view, WebResourceRequest request, WebResourceError error) {
            boolean remotePage = !ShellConfig.LOCAL_HOST.equals(request.getUrl().getHost());
            if (request.isForMainFrame() && config.isRemote() && remotePage) {
                // Remote site is unreachable: show the bundled offline page (index.html).
                view.loadUrl(ShellConfig.LOCAL_ORIGIN + "/index.html");
            }
        }

        @Override
        public boolean onRenderProcessGone(WebView view, RenderProcessGoneDetail detail) {
            Log.e(TAG, "WebView renderer is gone, restarting the activity");
            root.removeView(webView);
            webView.destroy();
            webView = null;
            startActivity(new Intent(MainActivity.this, MainActivity.class));
            finish();
            return true;
        }
    }

    /** Returns true when the URL was handled outside of the WebView. */
    private boolean handleNavigation(Uri uri) {
        String scheme = uri.getScheme() == null ? "" : uri.getScheme().toLowerCase(Locale.ROOT);
        switch (scheme) {
            case "http":
            case "https":
                if (config.isAppHost(uri.getHost()) || !config.openLinksExternally) {
                    return false;
                }
                openExternal(new Intent(Intent.ACTION_VIEW, uri));
                return true;
            case "about":
            case "blob":
            case "data":
            case "javascript":
                return false;
            case "intent":
                openIntentUri(uri.toString());
                return true;
            default:
                openExternal(new Intent(Intent.ACTION_VIEW, uri));
                return true;
        }
    }

    private void openIntentUri(String url) {
        try {
            Intent intent = Intent.parseUri(url, Intent.URI_INTENT_SCHEME);
            intent.addCategory(Intent.CATEGORY_BROWSABLE);
            intent.setComponent(null);
            intent.setSelector(null);
            try {
                startActivity(intent);
            } catch (ActivityNotFoundException e) {
                String fallback = intent.getStringExtra("browser_fallback_url");
                if (fallback != null) {
                    handleNavigation(Uri.parse(fallback));
                } else {
                    toast(getString(R.string.shell_no_app));
                }
            }
        } catch (java.net.URISyntaxException e) {
            toast(getString(R.string.shell_no_app));
        }
    }

    private void openExternal(Intent intent) {
        try {
            startActivity(intent);
        } catch (ActivityNotFoundException e) {
            toast(getString(R.string.shell_no_app));
        }
    }

    // ------------------------------------------------------- chrome client

    private final class ShellChromeClient extends WebChromeClient {
        @Override
        public boolean onShowFileChooser(WebView view, ValueCallback<Uri[]> callback, FileChooserParams params) {
            if (fileCallback != null) {
                fileCallback.onReceiveValue(null);
            }
            fileCallback = callback;
            List<String> mimeTypes = new ArrayList<>();
            for (String accept : params.getAcceptTypes()) {
                for (String part : accept.split(",")) {
                    String type = part.trim().toLowerCase(Locale.ROOT);
                    if (type.isEmpty()) {
                        continue;
                    }
                    if (type.startsWith(".")) {
                        String mime = MimeTypeMap.getSingleton().getMimeTypeFromExtension(type.substring(1));
                        if (mime != null) {
                            mimeTypes.add(mime);
                        }
                    } else {
                        mimeTypes.add(type);
                    }
                }
            }
            Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
            intent.addCategory(Intent.CATEGORY_OPENABLE);
            if (mimeTypes.size() == 1) {
                intent.setType(mimeTypes.get(0));
            } else {
                intent.setType("*/*");
                if (!mimeTypes.isEmpty()) {
                    intent.putExtra(Intent.EXTRA_MIME_TYPES, mimeTypes.toArray(new String[0]));
                }
            }
            if (params.getMode() == FileChooserParams.MODE_OPEN_MULTIPLE) {
                intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true);
            }
            try {
                startActivityForResult(intent, REQUEST_FILE_CHOOSER);
                return true;
            } catch (ActivityNotFoundException e) {
                fileCallback = null;
                toast(getString(R.string.shell_no_app));
                return false;
            }
        }

        @Override
        public void onGeolocationPermissionsShowPrompt(String origin, GeolocationPermissions.Callback callback) {
            if (!declaredPermissions.contains(Manifest.permission.ACCESS_FINE_LOCATION)
                    && !declaredPermissions.contains(Manifest.permission.ACCESS_COARSE_LOCATION)) {
                callback.invoke(origin, false, false);
                return;
            }
            if (isGranted(Manifest.permission.ACCESS_FINE_LOCATION) || isGranted(Manifest.permission.ACCESS_COARSE_LOCATION)) {
                callback.invoke(origin, true, false);
                return;
            }
            pendingGeoOrigin = origin;
            pendingGeoCallback = callback;
            requestPermissions(new String[] {Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION},
                    REQUEST_GEOLOCATION);
        }

        @Override
        public void onPermissionRequest(PermissionRequest request) {
            runOnUiThread(() -> handleMediaRequest(request));
        }

        @Override
        public void onPermissionRequestCanceled(PermissionRequest request) {
            if (pendingMediaRequest == request) {
                pendingMediaRequest = null;
            }
        }

        @Override
        public void onShowCustomView(View view, CustomViewCallback callback) {
            if (customView != null) {
                callback.onCustomViewHidden();
                return;
            }
            customView = view;
            customViewCallback = callback;
            root.addView(view, new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
            webView.setVisibility(View.GONE);
            applySystemBars();
            root.requestApplyInsets();
            updateBackCallback();
        }

        @Override
        public void onHideCustomView() {
            hideCustomView();
        }

        @Override
        public boolean onConsoleMessage(ConsoleMessage message) {
            Log.d(TAG, message.message() + " (" + message.sourceId() + ":" + message.lineNumber() + ")");
            return true;
        }
    }

    private void hideCustomView() {
        if (customView == null) {
            return;
        }
        root.removeView(customView);
        customView = null;
        webView.setVisibility(View.VISIBLE);
        if (customViewCallback != null) {
            customViewCallback.onCustomViewHidden();
            customViewCallback = null;
        }
        applySystemBars();
        root.requestApplyInsets();
        updateBackCallback();
    }

    private void handleMediaRequest(PermissionRequest request) {
        List<String> grantable = new ArrayList<>();
        List<String> missing = new ArrayList<>();
        for (String resource : request.getResources()) {
            String permission = null;
            if (PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(resource)) {
                permission = Manifest.permission.CAMERA;
            } else if (PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(resource)) {
                permission = Manifest.permission.RECORD_AUDIO;
            }
            if (permission == null || !declaredPermissions.contains(permission)) {
                continue;
            }
            grantable.add(resource);
            if (!isGranted(permission)) {
                missing.add(permission);
            }
        }
        if (grantable.isEmpty()) {
            request.deny();
        } else if (missing.isEmpty()) {
            request.grant(grantable.toArray(new String[0]));
        } else {
            if (pendingMediaRequest != null) {
                pendingMediaRequest.deny();
            }
            pendingMediaRequest = request;
            pendingMediaResources = grantable;
            requestPermissions(missing.toArray(new String[0]), REQUEST_MEDIA);
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == REQUEST_GEOLOCATION && pendingGeoCallback != null) {
            boolean granted = isGranted(Manifest.permission.ACCESS_FINE_LOCATION)
                    || isGranted(Manifest.permission.ACCESS_COARSE_LOCATION);
            pendingGeoCallback.invoke(pendingGeoOrigin, granted, false);
            pendingGeoCallback = null;
            pendingGeoOrigin = null;
        } else if (requestCode == REQUEST_MEDIA && pendingMediaRequest != null) {
            List<String> allowed = new ArrayList<>();
            for (String resource : pendingMediaResources) {
                String permission = PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(resource)
                        ? Manifest.permission.CAMERA
                        : Manifest.permission.RECORD_AUDIO;
                if (isGranted(permission)) {
                    allowed.add(resource);
                }
            }
            if (allowed.isEmpty()) {
                pendingMediaRequest.deny();
            } else {
                pendingMediaRequest.grant(allowed.toArray(new String[0]));
            }
            pendingMediaRequest = null;
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode != REQUEST_FILE_CHOOSER) {
            super.onActivityResult(requestCode, resultCode, data);
            return;
        }
        if (fileCallback == null) {
            return;
        }
        Uri[] result = null;
        if (resultCode == RESULT_OK && data != null) {
            if (data.getClipData() != null) {
                int count = data.getClipData().getItemCount();
                result = new Uri[count];
                for (int i = 0; i < count; i++) {
                    result[i] = data.getClipData().getItemAt(i).getUri();
                }
            } else if (data.getData() != null) {
                result = new Uri[] {data.getData()};
            }
        }
        fileCallback.onReceiveValue(result);
        fileCallback = null;
    }

    // ------------------------------------------------------------ downloads

    private void onDownload(String url, String userAgent, String contentDisposition, String mimeType, long contentLength) {
        String fileName = FileSaver.sanitize(URLUtil.guessFileName(url, contentDisposition, mimeType));
        if (url.startsWith("data:")) {
            saveBytesAsync(() -> FileSaver.decodeDataUrl(url), fileName, FileSaver.mimeOfDataUrl(url));
        } else if (url.startsWith("blob:")) {
            String script = "fetch(" + jsString(url) + ").then(function(r){return r.blob();}).then(function(b){"
                    + "var f=new FileReader();f.onloadend=function(){AppBuilderAndroid.saveDataUrl(String(f.result),"
                    + jsString(fileName) + ",b.type||'');};f.readAsDataURL(b);});";
            webView.evaluateJavascript(script, null);
        } else if (url.startsWith("http://") || url.startsWith("https://")) {
            try {
                DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url));
                request.setMimeType(mimeType);
                request.addRequestHeader("User-Agent", userAgent);
                String cookies = CookieManager.getInstance().getCookie(url);
                if (cookies != null) {
                    request.addRequestHeader("Cookie", cookies);
                }
                request.setTitle(fileName);
                request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);
                if (Build.VERSION.SDK_INT >= 29 || isGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
                    request.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, fileName);
                } else {
                    request.setDestinationInExternalFilesDir(this, Environment.DIRECTORY_DOWNLOADS, fileName);
                }
                DownloadManager manager = (DownloadManager) getSystemService(DOWNLOAD_SERVICE);
                manager.enqueue(request);
                toast(getString(R.string.shell_download_started, fileName));
            } catch (RuntimeException e) {
                Log.e(TAG, "Download failed", e);
                toast(getString(R.string.shell_file_save_failed));
            }
        }
    }

    private interface BytesSupplier {
        byte[] get() throws Exception;
    }

    private void saveBytesAsync(BytesSupplier supplier, String fileName, String mimeType) {
        new Thread(() -> {
            try {
                String location = FileSaver.save(this, supplier.get(), fileName, mimeType);
                toast(getString(R.string.shell_file_saved, location));
            } catch (Exception e) {
                Log.e(TAG, "Saving " + fileName + " failed", e);
                toast(getString(R.string.shell_file_save_failed));
            }
        }, "appbuilder-save").start();
    }

    /** JavaScript bridge: window.AppBuilderAndroid (bundled pages and the configured site only). */
    private final class AndroidBridge {
        @JavascriptInterface
        public boolean saveDataUrl(String dataUrl, String fileName, String mimeType) {
            if (!config.isAppHost(currentHost) || dataUrl == null) {
                return false;
            }
            String mime = mimeType == null || mimeType.isEmpty() ? FileSaver.mimeOfDataUrl(dataUrl) : mimeType;
            return saveNow(() -> FileSaver.decodeDataUrl(dataUrl), fileName, mime);
        }

        @JavascriptInterface
        public boolean saveFile(String base64, String fileName, String mimeType) {
            if (!config.isAppHost(currentHost) || base64 == null) {
                return false;
            }
            return saveNow(() -> Base64.decode(base64, Base64.DEFAULT), fileName, mimeType);
        }

        @JavascriptInterface
        public String platform() {
            return "android";
        }

        private boolean saveNow(BytesSupplier supplier, String fileName, String mimeType) {
            try {
                String location = FileSaver.save(MainActivity.this, supplier.get(), fileName, mimeType);
                toast(getString(R.string.shell_file_saved, location));
                return true;
            } catch (Exception e) {
                Log.e(TAG, "Saving " + fileName + " failed", e);
                toast(getString(R.string.shell_file_save_failed));
                return false;
            }
        }
    }

    // ---------------------------------------------------------------- back

    private void handleBack() {
        if (customView != null) {
            hideCustomView();
        } else if (webView != null && webView.canGoBack()) {
            webView.goBack();
        }
        updateBackCallback();
    }

    private void updateBackCallback() {
        if (backCallbacks != null) {
            backCallbacks.setEnabled(customView != null || (webView != null && webView.canGoBack()));
        }
    }

    @Override
    @SuppressWarnings("deprecation")
    public void onBackPressed() {
        if (customView != null || (webView != null && webView.canGoBack())) {
            handleBack();
        } else {
            super.onBackPressed();
        }
    }

    // ----------------------------------------------------------- lifecycle

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        if (webView != null) {
            webView.saveState(outState);
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (webView != null) {
            webView.onResume();
        }
    }

    @Override
    protected void onPause() {
        if (webView != null) {
            webView.onPause();
        }
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        if (webView != null) {
            root.removeView(webView);
            webView.destroy();
            webView = null;
        }
        super.onDestroy();
    }

    // -------------------------------------------------------------- helpers

    private boolean isGranted(String permission) {
        return checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED;
    }

    @SuppressWarnings("deprecation")
    private Set<String> readDeclaredPermissions() {
        try {
            PackageInfo info = getPackageManager().getPackageInfo(getPackageName(), PackageManager.GET_PERMISSIONS);
            if (info.requestedPermissions != null) {
                return new HashSet<>(Arrays.asList(info.requestedPermissions));
            }
        } catch (PackageManager.NameNotFoundException e) {
            Log.e(TAG, "Cannot read own package info", e);
        }
        return Collections.emptySet();
    }

    private String readAsset(String name) {
        try (InputStream in = getAssets().open(name)) {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[8192];
            int read;
            while ((read = in.read(buffer)) > 0) {
                out.write(buffer, 0, read);
            }
            return new String(out.toByteArray(), StandardCharsets.UTF_8);
        } catch (java.io.IOException e) {
            return null;
        }
    }

    private void toast(String message) {
        runOnUiThread(() -> Toast.makeText(this, message, Toast.LENGTH_LONG).show());
    }

    private static String jsString(String value) {
        StringBuilder sb = new StringBuilder("'");
        for (char c : value.toCharArray()) {
            switch (c) {
                case '\'':
                    sb.append("\\'");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                default:
                    if (c < 0x20 || c == 0x2028 || c == 0x2029) {
                        sb.append(String.format(Locale.ROOT, "\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
            }
        }
        return sb.append('\'').toString();
    }
}
